<div class="section about"><div class="blk-1">

<h1 id="uist-2015-author-s-guide">UIST 2015 AUTHOR&#39;S GUIDE</h1>
<p>A companion document to the UIST 2015 <a href="call">Call for Participation</a><br>Also see the <a href="author-advice">Advice for a Successful UIST Submission</a>  </p>
<p>This guide describes the format, deadlines and other relevant information for submissions to UIST 2015. Authors submitting material to UIST 2015 are encouraged to use this guide to learn about the UIST review process and the submission requirements. For guidelines on how to improve the quality of your submission, see the <a href="author-advice">Advice for a Successful UIST Submission</a>.</p>
<h3 id="introduction">INTRODUCTION</h3>
<p>UIST features papers, demos, and posters, as described in the Call for Participation. While the material in this guide is primarily oriented towards paper authors, its general emphasis on quality and stringent review is also applicable to authors of demo and poster submissions. Accepted papers will be presented during three days of technical sessions at the conference and published in the conference proceedings.</p>
<h3 id="uist-requires-novel-manuscripts">UIST REQUIRES NOVEL MANUSCRIPTS</h3>
<p>Paper submissions must not have been published previously in the English language. A paper is considered to have been previously published if it has appeared in a peer-reviewed journal or meeting proceedings that is reliably and permanently available afterward in print or electronic form to non-attendees. This includes papers that are reviewed only as abstracts, but are published as a complete paper.</p>
<p>The paper cannot be considered a novel manuscript if it reports an incremental update or a small improvement of the previously published work. Although the paper can be based on the earlier archival publications by the authors, significant new developments and findings have to be reported for the paper to be considered a novel manuscript. As a rule of thumb a paper has to include about 70% new material to be considered a novel contribution. We also encourage the authors to submit a complete work rather than dividing it into smaller pieces.  </p>
<p>For UIST submission purposes, a paper is not considered to have been previously published if it was presented earlier in forms explicitly labeled as &quot;non-archival&quot;, even if they are, in fact archived. This includes for example CHI extended abstracts (including alt.chi, works-in-progress, posters, demos, etc), SIGGRAPH Emerging Technology, and UIST posters and demos. Work that builds on previous non-archival work should typically contain at least 30% new material. However, authors must cite this previous work in their manuscript. If you are unsure about whether something is considered archival, please contact <a href="mailto:program2015@uist.org">program2015@uist.org</a>.
Authors wishing to submit work containing substantial portions of work published elsewhere also need to check their copyright agreement with the original publisher to make sure that this is permissible according to that agreement.</p>
<h3 id="re-publication-of-work-in-english-that-was-previously-published-in-another-language">RE-PUBLICATION OF WORK IN ENGLISH THAT WAS PREVIOUSLY PUBLISHED IN ANOTHER LANGUAGE</h3>
<p>English is considered the international language of ACM SIGCHI and its journals and conferences. Work that has previously been presented or published in a language other than English may be translated and presented or published in English in SIGCHI journals and conferences insofar as ACM SIGCHI is concerned. The original author should typically also be the author (or co-author) of work translated into English, and it should be made clear that this is a translation. We encourage authors whose work was originally published in languages other than English do this if they feel their work is of sufficient relevance and quality to be useful to a wider international audience. Of course, it is not acceptable to translate the original work of another author and present it as one&#39;s own. Authors wishing to publish in English a work originally published elsewhere also need to check their original copyright agreement with the original publisher to make sure that this is permissible according to that agreement.</p>
<h3 id="uist-supports-sharing-preliminary-work">UIST SUPPORTS SHARING PRELIMINARY WORK</h3>
<p>UIST sees significant value in sharing early work through posters, demos, and informal venues like technical reports. Indeed, UIST strongly encourages the submission of exciting, early research as a UIST poster or demo. Sharing preliminary research through these short, lightly reviewed work-in-progress or extended-abstract venues does not inhibit subsequent publication at UIST - provided that the UIST submission makes a contribution beyond (i.e., provides more or newer information than) the previous, shorter document. Such documents, which typically appear in the adjunct proceedings, are not considered prior publications, and thus do not preclude submission of a paper on the same topic by the same authors. Prior work should of course be referenced appropriately.</p>
<h3 id="concurrent-submission-is-prohibited">CONCURRENT SUBMISSION IS PROHIBITED</h3>
<p>A paper identical or substantially similar (or even a subset or superset) in content to one submitted to UIST must not be simultaneously under consideration at another conference or journal during the entire duration of the UIST review process (i.e., from the submission deadline until the notification of decisions are emailed to authors). This restriction applies even if the overlap in review timelines between UIST and another venue is just a few days or a few hours, and even if it is your intention to withdraw the submission from the other venues as soon as it is accepted by one of them. This restriction also applies even if the other venue allows simultaneous submission. UIST reviewers are often familiar with the papers under review at other related conferences and journals; as such, submissions that are substantially similar run the risk of being rejected by UIST and the other venues on grounds of duplication alone.</p>
<h3 id="revision-for-journals-is-encouraged">REVISION FOR JOURNALS IS ENCOURAGED</h3>
<p>You are encouraged to submit a revised and extended version of your UIST paper to a journal such as ACM Transactions on Computer-Human Interaction or Human-Computer Interaction after it has been presented at the conference.</p>
<h3 id="anonymous-submission-process">ANONYMOUS SUBMISSION PROCESS</h3>
<p>Paper submissions are anonymous. You are required to make a reasonable effort to purge identifying information from your submission:</p>
<h4 id="what-does-anonymous-mean-for-uist-submissions-">What does anonymous mean for UIST submissions?</h4>
<p>Primarily -- as with CHI -- it means that submissions must remove all author and institutional information from the title and header area of the first page of the paper. Author information should also be removed from submitted supplementary materials, in particular, videos. Submissions that do not do so may be rejected without review.</p>
<p>Furthermore, <b>all references must remain intact</b>. If you previously published a paper and your current submission builds on that work, the complete reference with author&#39;s name must appear in the references. Blank references (e.g., &quot;12. REMOVED FOR REVIEWING&quot;) should be avoided and authors must refer to their previous work in the third person (e.g. &quot;We build on prior work by Smith et al. [X] but generalize their algorithm to new settings.&quot;). Further suppression of identity in the body of the paper, while encouraged, is left to the authors&#39; discretion.</p>
<h4 id="what-if-the-work-i-am-writing-about-is-widely-publicized-already-e-g-a-website-an-application-or-a-performance-">What if the work I am writing about is widely publicized already (e.g., a website, an application, or a performance)?</h4>
<p>While the details of anonymization in the body of the paper are ultimately left to the authors&#39; discretion, we understand that some work is difficult (or impossible) to anonymize without degrading the quality of the writing. In these cases, we encourage the authors to ensure that details relevant for review of this paper are included.</p>
<h4 id="am-i-allowed-to-publicize-my-work-while-the-review-process-is-ongoing-">Am I allowed to publicize my work while the review process is ongoing?</h4>
<p>While publicizing and promoting work during the review process goes against the spirit of anonymous review, we understand that there are competing interests that make publicity important. The UIST community has agreed that such publicity should not be explicitly prohibited or penalized. However, we encourage authors to wait until the review process is over to publicize their work.</p>
<h4 id="why-did-uist-adopt-this-particular-strategy-of-lightweight-anonymization-">Why did UIST adopt this particular strategy of lightweight anonymization?</h4>
<p>UIST has a long tradition of excellent, thoughtful reviewing. This policy seeks to balance two goals. The first goal is to emphasize for all parties involved that reviews assess the content of a submission, not its authors. This is why names must be omitted from the masthead and reasonable efforts to maintain anonymity in the body of the paper should be taken. The second goal is to encourage papers that clearly explain the research. Sometimes doing so requires (at least implicitly) disclosing information about the authors or an institution.
If you have comments or questions about this policy, please email <a href="mailto:program2015@uist.org">program2015@uist.org</a>.
These rules apply to papers only. Submissions to the Posters, Demos, and Doctoral Symposium tracks should follow the anonymization guidelines in the respective calls for those tracks.</p>
<h3 id="the-reviewing-process">THE REVIEWING PROCESS</h3>
<p>The UIST review process is confidential and confidentiality of submissions is maintained from their submission to their publication date (typically the date of the first day of the conference).  </p>
<p>The Program Committee and a set of external reviewers, both consisting of recognized experts, will review submitted papers. Then, at their meeting (June 25-26, 2015), the committee will select those papers to be presented at UIST 2015.
For 2015 the Committee will be using the following process:</p>
<ul>
<li><b>1AC and 2AC Assignment:</b> In the week following the submission deadline, the Papers Chairs will assign each submitted paper to a primary reviewer (1AC) and a secondary reviewer (2AC) who are both members of the Program Committee. Papers that are inappropriate may be rejected during this assignment process, without being sent to a primary reviewer. Papers will normally be rejected at this stage only if they are clearly off-topic for UIST, if they are incomplete or clearly violate rules of this authorsâ€™ guide, or if they are discovered to have been published previously or to have been submitted simultaneously to another conference or journal.</li>
<li><b>Desk Rejections:</b> The primary reviewer may, upon conferring with the secondary reviewer and the Papers Chairs, recommend a paper be rejected without additional review. A paper will normally be rejected at this stage only if it falls into one of the categories listed above, but this fact was not detected during the initial paper assignment. It is possible, although unlikely, that a paper may also be rejected at this stage if it solves a problem that is known to be already solved; or if it does not cite (and the authors seem unaware of) important prior work on the same problem and doesn&#39;t address how it is different; or if it has no evaluation via proof, experiment, or analysis when such is required; if it is solving a problem sufficiently minor that the senior reviewers do not believe that it belongs in the program; if its overall level of quality is clearly not appropriate for UIST; or if it addresses a topic that is clearly outside the purview of UIST.</li>
<li><b>External Reviewer Assignment:</b> The primary reviewer distributes each paper to two additional experts, called external reviewers. The secondary reviewer also distributes the paper to one additional external reviewer. Thus, each paper submitted for review will be seen by five different people. This assignment process aims to reduce the impact of any single person on the final outcome for the paper by letting two different people (1AC and 2AC) assign external reviewers.</li>
<li><b>Reviews before Rebuttal:</b> The three external reviewers will write full reviews. Thus, at least three full reviews are written for each paper. The primary reviewer knows the identities of the authors of the papers, but the external reviewers do not. The 1AC will summarize the external reviewer sentiment in the meta review section of their review. If there is substantial disagreement among the external reviewers, the 1AC will prepare a full review of the paper.</li>
<li><b>Discussion before Rebuttal:</b> Between the review submissions and rebuttal phases, the 1AC may elect to begin a discussion amongst the reviewers (ACs and externals) to clarify reviews and strive for consensus.</li>
<li><b>Rejection Threshold:</b> After the primary and external reviewers complete their reviews, any paper for which all reviews fall below a threshold will be rejected. These papers will not have a rebuttal or be discussed at the PC meeting. Authors of the rejected papers will receive notifications at this point and can submit the work to other venues. Authors of all papers that are above the rejection threshold will have a chance to write a rebuttal.</li>
<li><b>Rebuttal:</b> After the 3 reviews and 1 meta review are complete, reviews will be distributed to authors. Authors will have 7 days to submit a rebuttal if they feel that the reviewers have made substantive errors, or to answer specific questions posed by the reviewers. We encourage the submission of a rebuttal regardless of the scores that authors receive in case the concerns of reviewers comes up in discussion at the Program Committee meeting. The rebuttal period will be from June 3 through June 10, 2015. The rebuttal is confined to 5000 characters in length and must be self-contained. For instance, URLs to additional material are not allowed. The rebuttal period is for addressing factual errors in the reviews and for responding to specific questions for clarification raised by reviewers. Revised text and other new materials can only be included if explicitly requested by reviewers and must be limited to only answer their questions. Any other novel material will be disregarded by the reviewers and Program Committee.</li>
<li><b>Post-Rebuttal Meta Reviews:</b> After the rebuttal, the primary reviewer will have a chance to revise the meta reviews taking into account the rebuttal, and the 2AC will also prepare a meta review, but it can be very short (e.g., &quot;This is great work, reviewers are all positive and I recommend acceptance&quot;). The 2AC will prepare a full review if they are in substantial disagreement with the overall reviewer sentiment. In some cases, a third reviewer from the Program Committee may be assigned based on requests by the 1AC and 2AC.</li>
<li><b>Post-Rebuttal Discussion Stage:</b> Between the end of the rebuttal submission and committee meeting, the reviewers (ACs and externals) will read the authorsâ€™ rebuttals, confer intensively about the papers, and prepare a recommendation for the committee meeting by June 24, 2015. Since the external reviewers do not know the names of the authors, the authors should maintain anonymity in their rebuttals. In addition, the external reviewers do not know each other&#39;s identities, so they too must maintain anonymity during the discussion. The preliminary recommendation agreed on at this stage will be either accept, reject, or if agreement on a recommendation cannot be reached, a third option is to table the paper for further review and discussion.</li>
<li><b>Program Committee Meeting:</b> The full Program Committee meets June 25-26, 2015, to determine acceptance or rejection of each paper. In cases where a consensus on a paper was not reached during the pre-meeting discussion phase, additional committee members may read the paper, and their evaluations will be taken into account in the decision.  </li>
</ul>
<h3 id="possible-outcomes-for-a-paper">POSSIBLE OUTCOMES FOR A PAPER</h3>
<p>Email notifications of the Program Committee&#39;s decisions should be sent no later than June 27, 2015. Full reviews, which may have changed due to the rebuttal, online discussion, and discussion at the committee meeting, will be sent by June 30, 2015. The notifications will place each paper in one of the following two categories:</p>
<ul>
<li><b>Rejected</b></li>
<li><b>Conditionally accepted</b>  </li>
</ul>
<p><b>Conditionally accepted papers</b> undergo a second review process in which a referee (an associate chair of the Program Committee) verifies that the final version of the paper is acceptable (that any required changes have been made, and that other changes made by the authors, perhaps in response to reviewer comments, have not compromised the paper in any way). The length of the camera-ready copy (rounded up to the nearest page) must be less than or equal to the length of the original submission unless there is a strong justification to increase the length of the manuscript, which should be agreed upon by the primary reviewer. This second and final stage determines the final acceptance status of all papers. The referees&#39; decisions are final. Papers that do not satisfy the referees in the second stage of review and/or that are not uploaded in final form by the final deadline of July 24, 2015, together with the original or revised versions of the submitted supplementary material, will be rejected. Accepted papers will appear in the conference proceedings.</p>
<h3 id="types-of-contributions">TYPES OF CONTRIBUTIONS</h3>
<p>There are many types of valid contributions to UIST, including new algorithms, techniques, hardware, theoretical models, systems and applications. We will do our very best to ensure reviewers understand that there are many ways for a paper to make a significant contribution to UIST, and that papers should be reviewed according the nature of their contributions. In particular, our community has identified systems and applications papers as particularly challenging to write and evaluate. For authors and reviewers of such papers, we recommend consulting articles written on how to evaluate systems research and how to write systems papers:</p>
<p>Levin, Roy, and David D. Redell. <a href="https://www.usenix.org/legacy/event/samples/submit/advice.html">How (and How Not) to Write a Good Systems Paper</a>. ACM SIGOPS Operating Systems Review 17.3 (1983): 35-40.</p>
<p>Olsen, D. R. 2007. <a href="http://icie.cs.byu.edu/paperPDFs/EvaluatingSystems.pdf">Evaluating Interface Systems Research</a>. In Proceedings of the 20th Annual ACM Symposium on User interface Software and Technology. UIST &#39;07. ACM, 251-258.</p>
<p>Another recent topic of discussion within our community has been the role of evaluations within HCI research. While user testing is not strictly required for UIST papers, authors should be careful not to make unsubstantiated claims for new techniques or systems which have not been tested. In general, authors and reviewers should consider what the appropriate method of validation is for the specific problem or research questions which their paper is addressing. For more advice on this topic, we recommend the following article:</p>
<p>Greenberg, S. and Buxton, B. 2008. <a href="http://dl.acm.org/citation.cfm?id=1357074">Usability evaluation considered harmful (some of the time)</a>. In Proceeding of the Twenty-Sixth Annual SIGCHI Conference on Human Factors in Computing Systems. CHI &#39;08. ACM, 111-120.</p>
<h3 id="supporting-video-material">SUPPORTING VIDEO MATERIAL</h3>
<p>See also the <a href="video-guide">video guide</a>
Since user interfaces are inherently interactive, authors are encouraged to include a video figure with their papers, which will be kept confidential during the review process. As with the rest of the paper, video figures should be anonymized.
Authors should make video figures short and accessible without being misleading. A video should give the same impression as a live demo. For example, a long computational pause can only be removed if its absence is made obvious through techniques such as a visual dissolve and a clear indication (verbal and/or visual) of how much time was removed. Videos about technology mock-ups should be clearly indicated as such. Mock-ups should be avoided when the video is about an implemented system. The video figure accompanying a submission for review is used only to help reviewers evaluate the submissions. Acceptable videos can be made without expensive production or special effects. A camcorder, tripod, and some planning can help guide the viewer&#39;s attention. A smooth zoom into the interaction area and then out to the full screen is often much more effective than a static screenshot. Show how the user manipulates the input devices if that is relevant.
Supporting video need not be stand-alone, because the reviewers will have the paper. While the paper should be understandable without the video, the paper may include references to the video. In particular, authors may use video sequences showing actual use of the proposed system to give readers and reviewers an impression of how the interaction unfolds like and/or how users responded to using the presented system. As video figures will be included with the paper in the ACM digital library, authors may assume that everyone who has the video has the paper, and vice versa. The burden is on the authors to ensure that videos figures are rendered in file formats and codecs that are accessible on all common platforms. Please see the video guide for more details.</p>

<h3 id="format">FORMAT</h3>
<p>All paper submissions must be made in the 2014 version of the <a href="http://www.sigchi.org/publications/chipubform">SIGCHI papers format.</a> Submitted papers may also include page numbers so the reviewers can more easily refer to portions. Detailed format instructions are available at the <a href="http://www.sigchi.org/publications/chipubform">SIGCHI conference publication format site</a>. Submissions must be in PDF format, and video submissions must be in one of the approved file formats. Submission details can be found at the <a href="http://www.precisionconference.com/~sigchi">UIST Electronic Submission site (http://www.precisionconference.com/~sigchi)</a>.</p>

<h3 id="copyright">COPYRIGHT</h3>
<p>Authors have the option to choose the level of rights management they prefer. ACM offers three different options for authors to manage the publication rights to their work.
Please consult the ACM Authors Site (<a href="http://authors.acm.org/">http://authors.acm.org/</a>).
<a href="http://chi2015.acm.org/authors/sigchi-submitter-agreement">The SIGCHI Submitter Agreement</a> also requires that authors hold copyright to the content of their submission, and will obtain appropriate permissions for any portions of the content that are copyrighted by others.</p>
<h3 id="history">HISTORY</h3>
<p>This document was last updated in January 2015 by Tovi Grossman and Bjoern Hartmann, who inherited it from Mira Dontcheva and Daniel Wigdor, who inherited it from Ivan Poupyrev and Takeo Igarashi, who inherited it from Hrvoje Benko and Celine Latulipe, who inherited it from Maneesh Agrawala and Scott Klemmer (who used material provided by Saul Greenberg), who inherited it from FranÃ§ois GuimbretiÃ¨re, who inherited it from Michel Beaudouin-Lafon, who inherited it from Ravin Balakrishnan and Chia Shen, who inherited it from Ken Hinckley and Pierre Wellner, who inherited it from Dan Olsen, who inherited it from Steve Feiner, who inherited it from Joe Konstan, who inherited it from Michel Beaudouin-Lafon, who inherited it from Ari Rapkin, who inherited it from Beth Mynatt, who inherited it from George Robertson, who inherited it from Marc H. Brown, who inherited it from George Robertson, who got lots of help on it from Steve Feiner, Brad Myers, Jock Mackinlay, Mark Green, Randy Pausch, Pierre Wellner, and Beth Mynatt.</p>



</div></div>
