<div class="section about"><div class="blk-1">


<h1 id="uist-2015-video-previews-details">UIST 2015 Video Previews Details</h1>
<h3 id="table-of-contents">Table of Contents</h3>
<ul>
<li><a href="#format">Format</a><ul>
<li><a href="#encoding-to-mpeg-4-h-264-mp4">Encoding to MPEG-4/H.264 (.mp4)</a></li>
<li><a href="#metadata-identification">Metadata (identification)</a></li>
<li><a href="#opening-title">Opening title</a></li>
<li><a href="#subtitles-and-captions">Subtitles and captions</a></li>
</ul>
</li>
<li><a href="#technical-guide">Technical Guide</a><ul>
<li><a href="#camera-basics">Camera Basics</a></li>
<li><a href="#audio">Audio</a></li>
<li><a href="#recording-computer-screens">Recording Computer Screens</a></li>
</ul>
</li>
<li><a href="#production-guide">Production Guide</a><ul>
<li><a href="#tell-a-story">Tell a story</a></li>
<li><a href="#presentation">Presentation</a></li>
<li><a href="#pacing">Pacing</a></li>
</ul>
</li>
<li><a href="#usability-testing">Usability Testing</a><ul>
<li><a href="#test-the-message">Test the message</a></li>
<li><a href="#test-the-compatibility">Test the compatibility</a></li>
</ul>
</li>
<li><a href="#copyright-sanity-check">Copyright &amp; Sanity Check</a><ul>
<li><a href="#review-acm-s-copyright-policies">Review ACM&#39;s Copyright Policies</a></li>
<li><a href="#sanity-check">Sanity check</a></li>
</ul>
</li>
</ul>
<h2 id="format">Format</h2>
<h3 id="encoding-to-mpeg-4-h-264-mp4">Encoding to MPEG-4/H.264 (.mp4)</h3>
<p>The Video Previews require MPEG-4 encoding using the H.264 codec (file format .mp4). Most video editing software provides an exporting option to MPEG-4/H.264. There are also a number of free encoding solutions you can use:</p>
<ul>
<li>For Windows users, <a href="http://www.freemake.com/">Freemake Video Converter</a> and <a href="https://handbrake.fr/">Handbrake</a> both provide good results.</li>
<li>For OSX users, we recommend <a href="https://handbrake.fr/">Handbrake</a> and other free converters available through the Apple App Store (e.g. <a href="http://www.mirovideoconverter.com/">Miro Video Converter</a>).</li>
<li>For Linux users, <a href="https://www.ffmpeg.org/">FFmpeg</a> is a well-known transcoding solution.</li>
</ul>
<p>Important: Encode your video using square pixel for the pixel aspect ratio to avoid your movie looking stretched when projected.</p>
<p><strong>Note:</strong> We do not endorse or are responsible for the use of any of the software mentioned in this guide.</p>
<h3 id="metadata-identification">Metadata (identification)</h3>
<p>Please remember to review the metadata properties of your digital file and insert appropriate identifying comments at the submission time: Author, Title, and Copyright information.</p>
<h3 id="opening-title">Opening title</h3>
<p>You must include the Title and Authors of the work at the beginning of the Video Preview, either as a title shot or as an overlay at the beginning of your video. Make sure that you leave the title for long enough of a duration to be read (~3s).</p>
<h3 id="subtitles-and-captions">Subtitles and captions</h3>
<p>You should include subtitles or captions to your video to guarantee that it can be consumed in places with ambient noise, where sound is unacceptable, and by hearing-impaired individuals. The following examples from the Video Gallery demonstrate good practices for captions and subtitles: <a href="http://www.youtube.com/watch?v=jJ9SKdEcIoQ">bottom banner</a>, <a href="http://www.youtube.com/watch?v=mlDHjLM4r9Q">top banner</a> and <a href="http://www.youtube.com/watch?v=_qwIplRTuSs">full part of the visual support</a>.</p>
<p><em>Important note:</em> Your captions do not necessarily have to stick to the voice over. Importantly, your video must be understandable without the sound. Here is <a href="http://www.youtube.com/watch?v=mEaUa1sdYZM">an excellent example</a> of a video preview that is equally understandable with or without the sound, while the captions are not subtitles.</p>
<h2 id="technical-guide">Technical Guide</h2>
<p>Current consumer hardware and software allow suitable production quality to be achieved outside of professional studios. The final production quality of a video mostly depends on the creativity and experience of the video maker.</p>
<h3 id="camera-basics">Camera Basics</h3>
<p>Use a tripod whenever possible to stabilize images. Contemporary hi-definition web-cameras (720p and up) are suitable for over-the-shoulder shoots.</p>
<p>Remember that the final picture will not be as clear as the picture in the monitor, so zoom in closer than might seem necessary, and make sure that no important elements are at the edge of the picture.</p>
<h3 id="audio">Audio</h3>
<p>We strongly recommend that you include a voice narration to your video. We recommend that you record the voice yourself rather than use a computer voice as generated by reader applications. If you have difficulties recording your voice, you may ask to a friend, or a trained reader to do so for you.</p>
<p>Try to avoid recording the noise of computer fans and disks. It is generally better to record the audio separately, by doing a voice-over in a studio or other quiet room. Audio editing tools like Audacity include a filter to eliminate background noise. Make sure you capture a sample of what the room sounds when it is quiet.</p>
<p>With a voice-over, you watch the video and record the sound that explains what is happening. Make sure that the discussion is synchronized with the action on the screen. Many successful videos use trained readers for the audio, which you can find by calling acting schools or radio stations.
If you are adding music to the video, place it on a separate track, so it will be easy to fade out music when narration begins, etc.</p>
<h3 id="recording-computer-screens">Recording Computer Screens</h3>
<p>Using a flat-panel LCD video monitor often leads to best results when filming a computer screen. Use a resolution that lets you capture text, lines, colors and animations accurately.</p>
<p>Other ways to capture a screen is using screen-capturing software. For Windows users, <a href="http://www.techsmith.com/camtasia.html">Camtasia</a>, <a href="http://camstudio.org/">Camstudio</a>, and <a href="http://www.microsoft.com/en-us/download/details.aspx?id=27870">MS Expression Encoder</a> are known to produce acceptable screen captures. For OSX, the <a href="https://www.apple.com/quicktime/">Quicktime player</a> already has a Screen Recording feature.</p>
<h2 id="production-guide">Production Guide</h2>
<h3 id="tell-a-story">Tell a story</h3>
<p>Previews are analog to an elevator pitch, without the benefit of a two-way dialog. There are many ways to organize a video presentation. Select a theme for the video and present your idea in a way that contributes to this goal. You will not have time to show and tell everything about your submission.</p>
<p>Concentrate on identifying what is novel and interesting. Emphasize the problems or issues being addressed. Present the concepts and principles upon which the work is based. Have a thread, a narrative, tell a (micro) story.</p>
<p>Your video should be understandable by itself. Your video should also be understandable to viewers who are not familiar with the subject.</p>
<h3 id="presentation">Presentation</h3>
<p>Use both the visual and audio capabilities of video. As the narrator, tell the viewer where to look and what to look for. Display screens have few natural navigation aids. Make your point once, and make it effectively; avoid being repetitious. Every second counts in a 30 seconds clip.</p>
<p>Pay attention to the background and colors; the eye is drawn to the most brightly colored part of the scene. Make the lightest and brightest part be the point of interest.</p>
<p>Avoid visual distractions, such as idly moving the mouse. Fades to black can be used as transitions between scenes, but they should not be overused. A full screen fade usually indicates a change in subject, time or place, and can be confusing when used elsewhere.</p>
<h3 id="pacing">Pacing</h3>
<p>The pacing of a video presentation must be appropriate to fit an idea, summary in 30 seconds: Not too slow to limit content, and not so fast that ideas cannot be absorbed. Please remember that your digital video will be accessed by an international audience, so speak clearly and more slowly than is natural to successfully convey your message.</p>
<p>You may wish to use someone with a very clear and understandable voice. Usually the most realistic and convincing advocate of an idea is the person responsible for the work being reported. Prepare a detailed script of the video and rehearse it thoroughly, in front of others if possible. This will help not only the delivery but also the clarity of your ideas.</p>
<h2 id="usability-testing">Usability Testing</h2>
<p>Please test your video for usability and accessibility just as you would (or expect from) any other product. Test both the legibility of the message and the compatibility of your video with a variety of computers, as detailed in the following sections.</p>
<h3 id="test-the-message">Test the message</h3>
<p>You can start off by testing your script with colleagues and friends. Is it interesting and understandable? Next you may want to storyboard your video. Do the cuts and transitions make sense; can you visualize how it will look? As well as being useful for usability testing, the storyboard should be an important part of your planning process. Next you should do rough cuts of the video. Do people want to see more talking head shots or fewer? Is the illustration of your material clear? Is the pace too fast or too slow? Are there any particular usability problems with specific segments of the video?</p>
<h3 id="test-the-compatibility">Test the compatibility</h3>
<p>Please ensure that you thoroughly usability test your video, including a final test to ensure that your digital video file will play on a variety of computers.</p>
<h2 id="copyright-sanity-check">Copyright &amp; Sanity Check</h2>
<h3 id="review-acm-s-copyright-policies">Review ACM&#39;s Copyright Policies</h3>
<p>As full part of your final submission, Video Previews are subject to ACM&#39;s copyright policies. Please review <a href="http://www.acm.org/publications/policies/copyright_policy">ACM&#39;s Copyright and Permission Policy</a> and <a href="http://www.acm.org/publications/third-party-material">ACM&#39;s Requirements about 3rd party material</a>.</p>
<p><strong>Note:</strong> You will be asked to confirm that you agree with these policies on the final submission form.</p>
<h3 id="sanity-check">Sanity check</h3>
<p>Please ensure that content is appropriate in terms of rights and taste, does not contain inappropriate language, viewpoints or imagery and is unlikely to cause offence to any individuals or groups either present at the conference or beyond.</p>
<p>This document draws and simplifies heavily on the Guides for Submission written by previous CHI and CSCW video chairs, originally published on the CHI&#39;99 Conference website. If you have any questions, please contact the video preview chairs at <a href="mailto:videopreviews@uist.org">videopreviews@uist.org</a>.</p>

</div></div>
